src/Entity/Panier.php
<?php

namespace App\Entity;

use App\Repository\PanierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use Symfony\Component\Serializer\Annotation\Ignore;


#[ORM\Entity(repositoryClass: PanierRepository::class)]
class Panier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $p_date = null;

    #[ORM\Column(nullable: true)]
    private ?float $total_price = null;

    #[ORM\ManyToOne]
    #[Ignore]
    private ?User $User = null;

    #[ORM\OneToMany(mappedBy: 'panier', targetEntity: MotosPanier::class ,  orphanRemoval: true)]
    #[Ignore]
    private Collection $MotosPaniers;

    public function __construct()
    {
        $this->MotosPaniers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPDate(): ?\DateTimeInterface
    {
        return $this->p_date;
    }

    public function setPDate(?\DateTimeInterface $p_date): self
    {
        $this->p_date = $p_date;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->total_price;
    }

    public function setTotalPrice(?float $total_price): self
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection<int, MotosPanier>
     */
    public function getMotosPaniers(): Collection
    {
        return $this->MotosPaniers;
    }

    public function addMotosPanier(MotosPanier $motosPanier): self
    {
        if (!$this->MotosPaniers->contains($motosPanier)) {
            $this->MotosPaniers->add($motosPanier);
            $motosPanier->setPanier($this);
        }

        return $this;
    }

    public function removeMotosPanier(MotosPanier $motosPanier): self
    {
        if ($this->MotosPaniers->removeElement($motosPanier)) {
            // set the owning side to null (unless already changed)
            if ($motosPanier->getPanier() === $this) {
                $motosPanier->setPanier(null);
            }
        }

        return $this;
    }
}

src/Form/PanierType.php
<?php

namespace App\Form;

use App\Entity\Panier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PanierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('p_date')
            ->add('total_price')
            ->add('User')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Panier::class,
        ]);
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Panier;
use App\Form\PanierType;
use App\Repository\PanierRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/panier')]
class PanierController extends AbstractController
{
    #[Route('/', name: 'app_panier_index', methods: ['GET'])]
    public function index(PanierRepository $panierRepository): Response
    {
        return $this->render('panier/index.html.twig', [
            'paniers' => $panierRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_panier_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PanierRepository $panierRepository): Response
    {
        $panier = new Panier();
        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $panierRepository->save($panier, true);

            return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('panier/new.html.twig', [
            'panier' => $panier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_panier_show', methods: ['GET'])]
    public function show(Panier $panier): Response
    {
        return $this->render('panier/show.html.twig', [
            'panier' => $panier,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_panier_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Panier $panier, PanierRepository $panierRepository): Response
    {
        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $panierRepository->save($panier, true);

            return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('panier/edit.html.twig', [
            'panier' => $panier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_panier_delete', methods: ['POST'])]
    public function delete(Request $request, Panier $panier, PanierRepository $panierRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$panier->getId(), $request->request->get('_token'))) {
            $panierRepository->remove($panier, true);
        }

        return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/panier/_delete_form.html.twig
<form method="post" action="{{ path('app_panier_delete', {'id': panier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ panier.id) }}">
    <button class="btn">Delete</button>
</form>

templates/panier/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/panier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Panier{% endblock %}

{% block body %}
    <h1>Edit Panier</h1>

    {{ include('panier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_panier_index') }}">back to list</a>

    {{ include('panier/_delete_form.html.twig') }}
{% endblock %}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier index{% endblock %}

{% block body %}
    <h1>Panier index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>P_date</th>
                <th>Total_price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for panier in paniers %}
            <tr>
                <td>{{ panier.id }}</td>
                <td>{{ panier.pDate ? panier.pDate|date('Y-m-d') : '' }}</td>
                <td>{{ panier.totalPrice }}</td>
                <td>
                    <a href="{{ path('app_panier_show', {'id': panier.id}) }}">show</a>
                    <a href="{{ path('app_panier_edit', {'id': panier.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_panier_new') }}">Create new</a>
{% endblock %}

templates/panier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Panier{% endblock %}

{% block body %}
    <h1>Create new Panier</h1>

    {{ include('panier/_form.html.twig') }}

    <a href="{{ path('app_panier_index') }}">back to list</a>
{% endblock %}

templates/panier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}
    <h1>Panier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ panier.id }}</td>
            </tr>
            <tr>
                <th>P_date</th>
                <td>{{ panier.pDate ? panier.pDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Total_price</th>
                <td>{{ panier.totalPrice }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_panier_index') }}">back to list</a>

    <a href="{{ path('app_panier_edit', {'id': panier.id}) }}">edit</a>

    {{ include('panier/_delete_form.html.twig') }}
{% endblock %}