src/Entity/Motos.php
<?php

namespace App\Entity;

use App\Repository\MotosRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MotosRepository::class)]
class Motos
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?int $kilometre = null;

    #[ORM\Column(nullable: true)]
    private ?float $price = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_imat = null;

    #[ORM\Column(nullable: true)]
    private ?float $power = null;

    #[ORM\ManyToOne]
    private ?Marque $Marque = null;

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getKilometre(): ?int
    {
        return $this->kilometre;
    }

    public function setKilometre(?int $kilometre): self
    {
        $this->kilometre = $kilometre;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDateImat(): ?\DateTimeInterface
    {
        return $this->date_imat;
    }

    public function setDateImat(?\DateTimeInterface $date_imat): self
    {
        $this->date_imat = $date_imat;

        return $this;
    }

    public function getPower(): ?float
    {
        return $this->power;
    }

    public function setPower(?float $power): self
    {
        $this->power = $power;

        return $this;
    }

    public function getMarque(): ?Marque
    {
        return $this->Marque;
    }

    public function setMarque(?Marque $Marque): self
    {
        $this->Marque = $Marque;

        return $this;
    }
}

src/Form/MotosType.php
<?php

namespace App\Form;

use App\Entity\Motos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MotosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('kilometre')
            ->add('price')
            ->add('date_imat')
            ->add('power')
            ->add('Marque')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Motos::class,
        ]);
    }
}

src/Controller/MotosController.php
<?php

namespace App\Controller;

use App\Entity\Motos;
use App\Form\MotosType;
use App\Repository\MotosRepository;
use PHPUnit\Util\Json;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\JsonEncode;

#[Route('/motos')]
class MotosController extends AbstractController
{
    #[Route('/', name: 'app_motos_index', methods: ['GET'])]
    public function index(MotosRepository $motosRepository): Response
    {
        return $this->render('motos/index.html.twig', [
            'motos' => $motosRepository->findAll(),
        ]);
       
    }
    
    #[Route('/new', name: 'app_motos_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MotosRepository $motosRepository): Response
    {
        $moto = new Motos();
        $form = $this->createForm(MotosType::class, $moto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $motosRepository->save($moto, true);

            return $this->redirectToRoute('app_motos_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('motos/new.html.twig', [
            'moto' => $moto,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_motos_show', methods: ['GET'])]
    public function show(Motos $moto): Response
    {
        return $this->render('motos/show.html.twig', [
            'moto' => $moto,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_motos_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Motos $moto, MotosRepository $motosRepository): Response
    {
        $form = $this->createForm(MotosType::class, $moto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $motosRepository->save($moto, true);

            return $this->redirectToRoute('app_motos_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('motos/edit.html.twig', [
            'moto' => $moto,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_motos_delete', methods: ['POST'])]
    public function delete(Request $request, Motos $moto, MotosRepository $motosRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$moto->getId(), $request->request->get('_token'))) {
            $motosRepository->remove($moto, true);
        }

        return $this->redirectToRoute('app_motos_index', [], Response::HTTP_SEE_OTHER);
    }

    
}

templates/motos/_delete_form.html.twig
<form method="post" action="{{ path('app_motos_delete', {'id': moto.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ moto.id) }}">
    <button class="btn">Delete</button>
</form>

templates/motos/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/motos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Motos{% endblock %}

{% block body %}
    <h1>Edit Motos</h1>

    {{ include('motos/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_motos_index') }}">back to list</a>

    {{ include('motos/_delete_form.html.twig') }}
{% endblock %}

templates/motos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Motos index{% endblock %}

{% block body %}
    <h1>Motos index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Kilometre</th>
                <th>Price</th>
                <th>Date_imat</th>
                <th>Power</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for moto in motos %}
            <tr>
                <td>{{ moto.id }}</td>
                <td>{{ moto.title }}</td>
                <td>{{ moto.description }}</td>
                <td>{{ moto.kilometre }}</td>
                <td>{{ moto.price }}</td>
                <td>{{ moto.dateImat ? moto.dateImat|date('Y-m-d') : '' }}</td>
                <td>{{ moto.power }}</td>
                <td>
                    <a href="{{ path('app_motos_show', {'id': moto.id}) }}">show</a>
                    <a href="{{ path('app_motos_edit', {'id': moto.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_motos_new') }}">Create new</a>
{% endblock %}

templates/motos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Motos{% endblock %}

{% block body %}
    <h1>Create new Motos</h1>

    {{ include('motos/_form.html.twig') }}

    <a href="{{ path('app_motos_index') }}">back to list</a>
{% endblock %}

templates/motos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Motos{% endblock %}

{% block body %}
    <h1>Motos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ moto.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ moto.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ moto.description }}</td>
            </tr>
            <tr>
                <th>Kilometre</th>
                <td>{{ moto.kilometre }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ moto.price }}</td>
            </tr>
            <tr>
                <th>Date_imat</th>
                <td>{{ moto.dateImat ? moto.dateImat|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Power</th>
                <td>{{ moto.power }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_motos_index') }}">back to list</a>

    <a href="{{ path('app_motos_edit', {'id': moto.id}) }}">edit</a>

    {{ include('motos/_delete_form.html.twig') }}
{% endblock %}