src/Entity/Cmd.php
<?php

namespace App\Entity;

use App\Repository\CmdRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CmdRepository::class)]
class Cmd
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $c_date = null;

    #[ORM\Column(nullable: true)]
    private ?float $c_totalPrice = null;

    #[ORM\Column(nullable: true)]
    private ?bool $payee = null;

    #[ORM\Column(nullable: true)]
    private ?bool $retrait = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Panier $Panier = null;

    #[ORM\ManyToOne]
    private ?User $User = null;

    #[ORM\ManyToOne]
    private ?Address $addressFact = null;

    #[ORM\ManyToOne]
    private ?Address $addressLiv = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCDate(): ?\DateTimeInterface
    {
        return $this->c_date;
    }

    public function setCDate(?\DateTimeInterface $c_date): self
    {
        $this->c_date = $c_date;

        return $this;
    }

    public function getCTotalPrice(): ?float
    {
        return $this->c_totalPrice;
    }

    public function setCTotalPrice(?float $c_totalPrice): self
    {
        $this->c_totalPrice = $c_totalPrice;

        return $this;
    }

    public function isPayee(): ?bool
    {
        return $this->payee;
    }

    public function setPayee(?bool $payee): self
    {
        $this->payee = $payee;

        return $this;
    }

    public function isRetrait(): ?bool
    {
        return $this->retrait;
    }

    public function setRetrait(?bool $retrait): self
    {
        $this->retrait = $retrait;

        return $this;
    }

    public function getPanier(): ?Panier
    {
        return $this->Panier;
    }

    public function setPanier(?Panier $Panier): self
    {
        $this->Panier = $Panier;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getAddressFact(): ?Address
    {
        return $this->addressFact;
    }

    public function setAddressFact(?Address $addressFact): self
    {
        $this->addressFact = $addressFact;

        return $this;
    }

    public function getAddressLiv(): ?Address
    {
        return $this->addressLiv;
    }

    public function setAddressLiv(?Address $addressLiv): self
    {
        $this->addressLiv = $addressLiv;

        return $this;
    }
}

src/Form/CmdType.php
<?php

namespace App\Form;

use App\Entity\Cmd;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CmdType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('c_date')
            ->add('c_totalPrice')
            ->add('payee')
            ->add('retrait')
            ->add('Panier')
            ->add('User')
            ->add('addressFact')
            ->add('addressLiv')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cmd::class,
        ]);
    }
}

src/Controller/CmdController.php
<?php

namespace App\Controller;

use App\Entity\Cmd;
use App\Form\CmdType;
use App\Repository\CmdRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/cmd')]
class CmdController extends AbstractController
{
    #[Route('/', name: 'app_cmd_index', methods: ['GET'])]
    public function index(CmdRepository $cmdRepository): Response
    {
        return $this->render('cmd/index.html.twig', [
            'cmds' => $cmdRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_cmd_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CmdRepository $cmdRepository): Response
    {
        $cmd = new Cmd();
        $form = $this->createForm(CmdType::class, $cmd);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cmdRepository->save($cmd, true);

            return $this->redirectToRoute('app_cmd_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cmd/new.html.twig', [
            'cmd' => $cmd,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cmd_show', methods: ['GET'])]
    public function show(Cmd $cmd): Response
    {
        return $this->render('cmd/show.html.twig', [
            'cmd' => $cmd,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_cmd_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cmd $cmd, CmdRepository $cmdRepository): Response
    {
        $form = $this->createForm(CmdType::class, $cmd);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cmdRepository->save($cmd, true);

            return $this->redirectToRoute('app_cmd_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cmd/edit.html.twig', [
            'cmd' => $cmd,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cmd_delete', methods: ['POST'])]
    public function delete(Request $request, Cmd $cmd, CmdRepository $cmdRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cmd->getId(), $request->request->get('_token'))) {
            $cmdRepository->remove($cmd, true);
        }

        return $this->redirectToRoute('app_cmd_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/cmd/_delete_form.html.twig
<form method="post" action="{{ path('app_cmd_delete', {'id': cmd.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cmd.id) }}">
    <button class="btn">Delete</button>
</form>

templates/cmd/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/cmd/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cmd{% endblock %}

{% block body %}
    <h1>Edit Cmd</h1>

    {{ include('cmd/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_cmd_index') }}">back to list</a>

    {{ include('cmd/_delete_form.html.twig') }}
{% endblock %}

templates/cmd/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cmd index{% endblock %}

{% block body %}
    <h1>Cmd index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>C_date</th>
                <th>C_totalPrice</th>
                <th>Payee</th>
                <th>Retrait</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for cmd in cmds %}
            <tr>
                <td>{{ cmd.id }}</td>
                <td>{{ cmd.cDate ? cmd.cDate|date('Y-m-d') : '' }}</td>
                <td>{{ cmd.cTotalPrice }}</td>
                <td>{{ cmd.payee ? 'Yes' : 'No' }}</td>
                <td>{{ cmd.retrait ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_cmd_show', {'id': cmd.id}) }}">show</a>
                    <a href="{{ path('app_cmd_edit', {'id': cmd.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_cmd_new') }}">Create new</a>
{% endblock %}

templates/cmd/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cmd{% endblock %}

{% block body %}
    <h1>Create new Cmd</h1>

    {{ include('cmd/_form.html.twig') }}

    <a href="{{ path('app_cmd_index') }}">back to list</a>
{% endblock %}

templates/cmd/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cmd{% endblock %}

{% block body %}
    <h1>Cmd</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cmd.id }}</td>
            </tr>
            <tr>
                <th>C_date</th>
                <td>{{ cmd.cDate ? cmd.cDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>C_totalPrice</th>
                <td>{{ cmd.cTotalPrice }}</td>
            </tr>
            <tr>
                <th>Payee</th>
                <td>{{ cmd.payee ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Retrait</th>
                <td>{{ cmd.retrait ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_cmd_index') }}">back to list</a>

    <a href="{{ path('app_cmd_edit', {'id': cmd.id}) }}">edit</a>

    {{ include('cmd/_delete_form.html.twig') }}
{% endblock %}